Fixed a couple breaking issues
LuvDaSun/angular-hal pull request #67
Opened 2017-08-03 16:47 UTC by benmarch

This is a fantastic library, but I had some issues after installing it:

* The response interceptor returns just a Resource, which does not contain all of the properties from the response. This is a problem because another plugin that I am using looks for the `config` property, and throws an error. I haven't fully tested my change, but it looks like adding the properties to the resource as non-enumerable fixes the problem with no side effects. I wanted to keep this change backwards-compatible, otherwise I would have returned the response and made `response.data` the Resource.
* This might have been caused by our Webpack config, but we were getting build errors when importing. I think it is because I am excluding anything under `node_modules` from Babel. I just changed package.json to point to the dev bundle.

Thank you for creating and maintaining this! Saved me so much time!

2017-08-03 21:11 UTC, maennchen requested changes
I don't like having those properties inside of the resource, even if they are non-enumerable. I'd rather create a breaking change that for example adds the resource onto the respone.

2017-08-03 21:11 UTC, maennchen commented on package.json
> +  "main": "dist/angular-hal.js",
The main property has to point to the index.js and not a generated dist file. If this doesn't work with your webpack config, I recommend changing the config.

2017-08-03 21:11 UTC, maennchen commented on package.json
> -    "build:dev": "./node_modules/.bin/browserify src/index.js -o dist/angular-hal.map.js  -t [ babelify --presets [ es2015 ] ] --s angularHal -d",
Why did you change the file paths?

2017-08-03 21:23 UTC, benmarch commented
Hey @maennchen, thank you for reviewing so quickly. I agree, I don't like the approach, I would be happy to change it so that the response is in tact but the data is the resource. I changed the file path because the dev file is more than just a source map file (no functional reason though).

I'll revert these changes and just submit the change to the interceptor. As you mentioned, I can get around the Webpack issue on my end, so that change is not really necessary (nor the filename change).

2017-08-04 06:55 UTC, agouriou commented
Hello,

Just to understand: @benmarch you did this change because another plugin setup another http interceptor  that requires `config` ?

2017-08-04 14:12 UTC, benmarch commented
Hey @agouriou, yes, that is exactly right. I'll have the changes in later today for your review.

2017-08-04 14:23 UTC, agouriou commented
What I did in a similar case was to register the interceptors in an order so that angular-hal's intercepter is the last one to operate. 

By doing so, all interceptors worked as expected since the initial `Response` object was only transformed to a `Resource` in the last step of interception.

Maybe this could suit your needs...

2017-08-04 14:35 UTC, benmarch commented
That was my first approach but since I don't have control over when either interceptor is registered, I couldn't figure out how to ensure the order. Did you have to manually order `$httpProvider.interceptors` in your config block?

I would rather not use this solution since it is still a bit of a hack. I think it is reasonable for a library to assume that a response object will be passed into a response interceptor, so I think it is best for angular-hal to uphold that assumption. I am setting up my changes in a way where if you use `$http` to request a resource then you will get the response object, but if you use `halClient` then you will get the resource as you do now. It should require very minimal changes to consumer code.

2017-08-04 14:46 UTC, maennchen commented
I think it would be a reasonable decision to move the resource into the response data and return the whole response object. This should suit both needs.

The reason I didn't implement it this way, is that I want the same interface for links and embeds. With embeds there would be no normal response since it requires no HTTP request.

If you can come up with a good solution to that problem, I'd be happy to accept a PR.

2017-08-04 15:10 UTC, benmarch commented
@agouriou @maennchen ready for your review. You can see from the changes to the test cases that consuming code will only have to make changes when using `$http` to request a resource. If developers followed your examples then it is likely that they only need to make a single change when requesting the API root resource. The `halResourceClient` and `halClient` APIs are unchanged, so there is still consistency between getting links and embedded resources.

2017-08-04 15:20 UTC, maennchen commented
I'm currently on vacation. I'll have a thoroughly look at it when I'm back home.

It looks good on first glance, thank you verry much.

2017-08-06 10:12 UTC, maennchen approved these changes

2017-08-06 10:12 UTC, merged

2017-08-07 16:16 UTC, benmarch commented
Thank you, @maennchen! Please let me know when I can update my app with the new version.

2017-08-07 17:07 UTC, maennchen commented
Could you create a migration guide and include it in the readme?

2017-08-07 17:10 UTC, benmarch commented
Sure, will this be a major release (3.0.0)?

2017-08-07 17:47 UTC, maennchen commented
Yes

2017-08-07 18:55 UTC, benmarch commented
Created #70 with updates to README.